# Generated by Django 5.0.4 on 2024-04-12 18:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Backend', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='screenshotmodel',
            name='activity',
        ),
    ]
