# Generated by Django 5.0.4 on 2024-04-12 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Backend', '0004_alter_weeklyactivity_activityhours'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weeklyactivity',
            name='weekEarned',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='weeklyactivity',
            name='weeksActivity',
            field=models.FloatField(default=0.0),
        ),
    ]
