# Generated by Django 5.0.4 on 2024-04-13 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Backend', '0005_alter_weeklyactivity_weekearned_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailyactivity',
            name='dailyHours',
            field=models.DurationField(),
        ),
    ]
