# Generated by Django 5.0.4 on 2024-04-13 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Backend', '0006_alter_dailyactivity_dailyhours'),
    ]

    operations = [
        migrations.AlterField(
            model_name='screenshotmodel',
            name='url',
            field=models.URLField(max_length=1000),
        ),
    ]
